---
- name: Execute reverse_copy_redhat.sh on remote host
  hosts: redhat  # This will apply to all hosts in the inventory
  become: yes
  tasks:
    - name: Execute reverse_copy_redhat.sh
      command: /audit/scripts/reverse_copy_redhat.sh  # Ensure this is the correct path to your script
      register: reverse_copy_result  # Register output for potential debugging

    - name: Display reverse_copy_redhat.sh output
      debug:
        var: reverse_copy_result.stdout

    - name: Display reverse_copy_redhat.sh error output
      debug:
        var: reverse_copy_result.stderr

