---
- name: Execute ubuntu_ubuntu.sh on remote host
  hosts: all  # This will apply to all hosts in the inventory
  tasks:
    - name: Execute ubuntu.sh
      command: /data/ubuntu.sh  # Ensure this is the correct path to your script
      register: ubuntu_result  # Register output for potential debugging

    - name: Display ubuntu.sh output
      debug:
        var: ubuntu_result.stdout

    - name: Display ubuntu.sh error output
      debug:
        var: ubuntu_result.stderr


